src/ArrayFire.jl

* Create generic `AFArray()`  
* Instead of using `rand` in for passing output, use `AFArray()`
* Also fixes #5

Add a generic AFArray constructor, use it in chol, lu, svd

---

src/ArrayFire.jl

This would allow one to execute iterations in parallel.

Add parallel loop

---

src/image.jl

Looks like all the filters could use some tests.

Fix `sobel`

---

src/config.jl

Fixes bug in config file. Fixes #69.

Fix the config file

---

README.md
src/ArrayFire.jl
src/device.jl
src/error.jl
src/wrap.jl

Add device code to change devices, fix depwarn in error display

---

src/linalg.jl

Make norm of Float32 return Float32

---

src/wrap.jl
test/runtests.jl

Fix ifft bug

---

.travis.yml
src/create.jl
src/signal.jl
src/wrap.jl

Closes #85 , #86. Also, updates ArrayFire version in Travis

Some fixes

---

src/create.jl

Fix false function

---

src/create.jl
src/math.jl
src/utils.jl
src/vector.jl
test/runtests.jl

As pointed out in #92, the functions can be better designed to use Julia's type inference. This PR begins the fixing.

Some type inference fixes - math functions

---

src/indexing.jl
test/runtests.jl

Fix indexing with booleans

---

src/ArrayFire.jl

just a pet peeve
close https://github.com/JuliaComputing/ArrayFire.jl/issues/84

remove unnecessary anon function in finalizer call

---

.travis.yml
src/indexing.jl
test/runtests.jl

Fix indexing bug

---

benchmarks/benchmark.jl

Fixes #117 
cc: @jpsamaroo @ViralBShah

Make matrix symmetric positive definite in benchmark

---

README.md

Update README to say `using` in basic usage

---

src/vector.jl
test/runtests.jl

Make sum type stable and add test

---

src/wrap.jl
test/runtests.jl

Fix fft! bug

---

src/array.jl
src/wrap.jl
test/array.jl
test/runtests.jl

This PR adds two things:
- Fix a segfault in diag_create
- Add range and linspace (which would close https://github.com/JuliaComputing/ArrayFire.jl/issues/169)
The proposed change to diag_create fixes a segfault which can occur when calling with an array of dimension 1.
Pre-fix:
```julia
julia> x = AFArray(randn(8))
AFArray: 8-element Array{Float64,1}:
0.94958 
0.57314 
-0.362604
0.115962
0.467327
1.34093 
-0.927704
-1.33555 
julia> diag_create(x, 0)
AFArray: 8-element Array{Float64,1}:
0.94958
0.0    
0.0    
0.0    
0.0    
0.0    
0.0    
0.0    
julia> Segmentation fault: 11
```
Post-fix:
```julia
julia> x = AFArray(randn(8))
AFArray: 8-element Array{Float64,1}:
0.185307 
-1.79244  
0.0999372
0.0126911
0.209253 
1.63831  
0.231278 
-0.243118 
julia> diag_create(x, 0)
AFArray: 8×8 …
```

add range/linspace

---

README.md

- one typo
- better format for list of supported functions

Fix format error on the README.md

---

src/array.jl
test/math.jl

I have added the functionality to compute the sum along a multiple dimensions.
I am actually not sure if it is a good implementation. Any suggestions for a better implementation?

Sum over an iterator

---

.gitignore
Project.toml

xref https://github.com/JuliaRegistries/General/pull/765#discussion_r284122824

Re-add compatibility bounds.
